
export interface UserProfile {
  name: string;
  role: string;
  status: 'ACTIVE' | 'PENDING' | 'SUSPENDED'; // RBAC Status
  fwiScore: number;
  treePoints: number;
  streakDays: number;
  level: number;
  monthlyIncome: number;
  availableEwa: number; // The calculated limit based on days worked
}

export type EwaStatus = 'pending_approval' | 'processing_transfer' | 'disbursed' | 'rejected';

export interface EwaRequest {
  id: string;
  amount: number;
  date: string;
  status: EwaStatus;
  fee: number;
  estimatedArrival: string;
}

export interface Transaction {
  id: string;
  merchant: string;
  amount: number;
  category: string;
  date: string;
  isDiscretionary: boolean;
  aiConfidence?: number;
}

export interface ExpenseAnalysis {
  merchant: string;
  amount: number;
  category: string;
  isDiscretionary: boolean;
  confidence: number;
  dateContext?: 'today' | 'yesterday' | 'past';
  // New Operational Hub Fields
  budgetImpact?: {
    categoryLimit: number;
    remainingAfter: number;
    percentUsed: number; // 0-100
    status: 'safe' | 'warning' | 'critical';
  };
  suggestedAction?: {
    type: 'save' | 'offer';
    title: string;
    description: string;
    actionId: string; // Links to MarketOffer ID or Goal ID
  };
}

export interface MarketOffer {
  id: string;
  title: string;
  description: string;
  costPoints: number;
  category: 'Financial' | 'Lifestyle' | 'Emergency' | 'Investment';
  targetFwiSegment: 'low' | 'mid' | 'high' | 'all';
  discountValue?: string;
  origin: 'corporate' | 'global';
}

export interface FinancialGoal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string;
  category: 'Emergency' | 'Vacation' | 'Purchase' | 'Investment';
  priority: boolean;
  lastContribution?: number; // timestamp
}

export interface B2BMetric {
  metric: string;
  value: string | number;
  trend: 'up' | 'down' | 'neutral';
  delta: string;
}

export interface EmployeeRisk {
  id: string;
  name: string;
  department: string;
  fwiScore: number;
  absenteeismRisk: 'Low' | 'Medium' | 'High' | 'Critical';
  ewaFrequency: number;
  workModality: 'Remote' | 'Hybrid' | 'On-site';
  age: number;
}

export interface ChatMessage {
  id: string;
  text: string;
  sender: 'user' | 'ai';
  timestamp: number;
}

export interface AiAdviceCard {
  id: string;
  type: 'risk' | 'opportunity' | 'insight';
  title: string;
  description: string;
  actionLabel: string;
  icon?: string;
}

export enum ViewMode {
  EMPLOYEE = 'EMPLOYEE',
  B2B_ADMIN = 'B2B_ADMIN',
  MERCHANT = 'MERCHANT',
}

export enum MerchantRole {
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
  VIEWER = 'VIEWER'
}

export interface MerchantProfile {
  id: string;
  name: string;
  level: 'Gold' | 'Silver' | 'Bronze';
  role: MerchantRole;
}

// --- BACKEND HANDOFF CONTRACTS (DTOs) ---

// Response expected from /api/v1/user/sync
// Used after any critical action (Expense, EWA, Goal) to refresh client state
export interface UserSyncResponse {
  success: boolean;
  userProfile: UserProfile;
  alerts: AppAlert[]; // New alerts generated by the action
  updatedTransactions?: Transaction[]; 
}

export interface AppAlert {
  id: string;
  type: 'liquidity_warning' | 'fwi_drop' | 'achievement' | 'policy_rejection';
  message: string;
  severity: 'info' | 'warning' | 'critical';
}

// Data Moat Event Payload Structure
export interface MoatEventPayload {
  event_name: string;
  timestamp: number;
  user_id_hash?: string;
  fwi_score_context?: number;
  metadata: Record<string, any>;
}